language: node_js
node_js:
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
script:
  - npm run build  # build
  - npm run coverage  # run mocha unit tests with coverage
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
